---
title: "Computing Project"
author: "Damon Landis"
date: "3/29/2021"
output: html_document
---
Damon Landis: The goal of this project is to determine the more efficient data analysis tool for a capstone experiment. Our group is split into two subgroups with one using R and one using Mathematica. Currently, we are making sure we are comfortable with each program and waiting for the polymerase chain reaction capstone project to wrap up so we can write our separate programs. Personally, I have researched the differences between the two programs and have also read through guides on the R program itself.

Aaron Bowlin: The goal of our group’s project is not only to write a couple program’s that can deal with the data created by a capstone project, but to determine which programming language (R or Mathematica) would perform better for this specific given project. We must wait for the polymerase chain reaction experiment to finish in order to have the data in order to actually write the program. However, I have researched articles and watched tutorial videos on R programming and plan on meeting with Dr. Malmberg soon. regarding the program.

Jackson Landsteiner: The group was split into two sub groups. I was apart of the r markdown group, so while the capstone project was finishing, I have been familiarizing myself with the different functions to properly utilize the coding. Once the information is obtained it’ll be placed into the code. 

Josh Spears: The goal of our project is to analyze data in a capstone project comparing methods of R and Mathematica. Our sub group is going to be performing the analysis using Mathematica. So far, I have downloaded Mathematica and researched on their website how to use it for statistical analysis. We are waiting on a capstone project to conclude so we can perform analysis on it.

Dakota Clark: The overall goal of our experiment is to perform data analysis of a capstone project using R and Mathematica, and then compare the language used in each. To date, I have reviewed directions and resources describing the use of Mathematica to analyze data (which is the program my group will be using), and I have downloaded Mathematica onto my computer. No analysis has been able to be performed yet as we are waiting for the capstone project to conclude.

Eli Paul: I downloaded a 15 day trial for Mathematica and am working on getting comfortable with it. A way to get Mathematica for a longer period of time will be necessary though. Additonally, we are using my capstone project for this computing project.
